### ISSUE TITLE
Ignore newline characters while parsing

### ISSUE THREAD

**Issue by araghon007** [SoftCircuits/HtmlMonkey#2]
I'm using HttpClient, which sometimes returns a document including line breaks(\r\n). This throws off the parser in multiple ways. It considers most of the newline characters as their own elements, and sometimes even manages to mess up the parsed tag. Even the included example document is parsed incorrectly.
![image](https://user-images.githubusercontent.com/10870921/153397506-dd20732e-1e19-4b75-bdc2-586514f3360a.png)
I had to build the test program using .NET 5.0, instead of 6.0, and for my own program, I'm using .NET Framework 4.7.2
I'm also using Windows 10
Is this an issue specific to Windows (perhaps the \r character) and can it be solved, or do I just have to remove the newline characters from the input string manually?

**Comment by araghon007** [comment]
I also think this might apply to tab character (\t) but I haven't tested that properly yet

**Comment by SoftCircuits** [comment]
Text that is not part of a tag or other special element is a text element. This includes newline and tab characters. And if you look carefully, you can see it also includes spaces.

This is by design, and is also a characteristic of other HTML and XML parsers.

If you think it's not parsing some tags correctly, you'll need to do a much better job of showing what it does wrong.

**Comment by araghon007** [comment]
I see, I didn't know that. I know there was one edge case, where the closing tag wasn't detected, but that may have as well been a malformed html.
